### ISSUE TITLE
[flutter_map_cache] CachedTileProvider.dio - options not taken into account

### ISSUE THREAD

**Issue by Thelm76** [josxha/flutter_map_plugins#12]
With the `CachedTileProvider`, the `dio` options are overrode.

Due to the way the `CachedTileProvider` constructor is written, the `dioOptions` passed to the `Dio()` constructor are not taken into account.

Indeed, if `dioOptions` is null, the `CachedTileProvider` body overrides the options with `BaseOptions`

**Comment by josxha** [comment]
Version 1.4.3 is released on pub.dev👍
