### ISSUE TITLE
[BUG] MapCompass alignment not working

### ISSUE THREAD

**Issue by DmitriySimonov** [josxha/flutter_map_plugins#39]
### Package

flutter_map_compass

### Bug Description

MapCompass alignment not working

### Steps to Reproduce

Add code MapCompass in FlutterMap

flutter doctor
```
[✓] Flutter (Channel stable, 3.19.5, on Ubuntu 22.04.4 LTS 5.15.0-101-generic, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.2)
[✓] Connected device (3 available)
[✓] Network resources

```

### Expected Results

The compass is expected to be top left

### Actual Results

But the compass on the top right
![Screenshot_20240403_152806](https://github.com/josxha/flutter_map_plugins/assets/124057357/8817653d-ca5b-4c74-87a0-aa951ebfd36e)

### Code Sample

```dart
FlutterMap(
        options: MapOptions(),
        children: [
          ...
          MapCompass(
            icon: SvgPicture.asset(Const.IMAGE_COMPASS, height: sizeCompassMaker),
            alignment: Alignment.topLeft,
          ),
        ],
      ),
```

### Platforms

android

**Comment by josxha** [comment]
Thanks a lot for submitting the bug report @DmitriySimonov. I'll be fixed within https://github.com/josxha/flutter_map_plugins/issues/39.
