### ISSUE TITLE
[BUG] Example: Add layerMode: VectorTileLayerMode.vector

### ISSUE THREAD

**Issue by eliabieri** [josxha/flutter_map_plugins#43]
### Package

vector_map_tiles_pmtiles

### Bug Description

In the example of `vector_map_tiles_pmtiles` there is no `layerMode: VectorTileLayerMode.vector` in the constructor of `VectorTileLayer`. Isn't this a bug?

### Steps to Reproduce

1. Go to [example](https://github.com/josxha/flutter_map_plugins/blob/main/vector_map_tiles_pmtiles/example/example.md)

### Expected Results

```dart
VectorTileLayer(
        // the map theme
        theme: mapTheme,

        tileProviders: TileProviders({
          // the awaited vector tile provider
          'protomaps': tileProvider,
        }),
        layerMode: VectorTileLayerMode.vector,

        // disable the file cache when you change the PMTiles source
        // fileCacheTtl: Duration.zero,
      ),
```

### Platforms

all

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/josxha) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/josxha/flutter_map_plugins/issues/43">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/josxha/flutter_map_plugins/issues/43/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/josxha/flutter_map_plugins/issues/43/pledge.svg">
</picture>
</a>

**Comment by josxha** [comment]
Hi Elia, thanks for opening a bug report. Not sure why the property can't be found in your implementation but it should be still available.

https://github.com/greensopinion/flutter-vector-map-tiles/blob/f3fdbd21b8608dae7f431a54a2a8bdc4500e6c0d/lib/src/vector_tile_layer.dart#L107-L109

But you can remove it since it isn't required for the implementation.
