### ISSUE TITLE
[FEATURE] Support for loading pmtiles from assets

### ISSUE THREAD

**Issue by baileyheading** [josxha/flutter_map_plugins#44]
### Package

vector_map_tiles_pmtiles

### Feature Description

I've noticed this comment in the documentation:

"/// The source can be a PMTiles file that is either hosted or local on 
/// your file system. flutter assets however are not supported."

What is the cause of this limitation and can it be overcome?

If I wanted to use this in ios for example, are there any workarounds? (other than perhaps copying from assets to documents on the first init)

### Feature importance

(1) would be nice to have

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/josxha) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/josxha/flutter_map_plugins/issues/44">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/josxha/flutter_map_plugins/issues/44/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/josxha/flutter_map_plugins/issues/44/pledge.svg">
</picture>
</a>

**Comment by josxha** [comment]
Hi @baileyheading, 

> What is the cause of this limitation and can it be overcome?

The PMTiles format requires partial file reads. As far as I know, you can only read a complete file from the flutter assets and not just some bytes. There is an open flutter issue here:
- https://github.com/flutter/flutter/issues/73322

> If I wanted to use this in ios for example, are there any workarounds? (other than perhaps copying from assets to documents on the first init)

The mentioned workaround is deponstrated in the example app for mbtiles too:
https://github.com/josxha/flutter_map_plugins/blob/8c671c902db76868f11e7e816891cb7089f997ea/example/lib/common/utils.dart#L6C1-L22C2

It all comes down to the size of your pmtiles file. If it's small it's probably fine to have it stored twice on the device. But if it has a reasonable size it's probably better to put it on some webserver or object storage and download it from there.

I hope these informations help.

**Comment by baileyheading** [comment]
Thanks, just the info I was looking for. That flutter issue is quite old now 😫

**Comment by josxha** [comment]
No problem, I'll close this issue for now because I don't think we can add this feature any time soon but we can re-open it again once flutter has support for it. 👍
