### ISSUE TITLE
Update ProtomapsThemes to  version 4

### ISSUE THREAD

**Issue by AntonZN** [josxha/flutter_map_plugins#46]
### Package

other

### Feature Description

Will there be an update to the protomaps_themes styles to version 4 or 4.1?

### Feature importance

(1) would be nice to have

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/josxha) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/josxha/flutter_map_plugins/issues/46">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/josxha/flutter_map_plugins/issues/46/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/josxha/flutter_map_plugins/issues/46/pledge.svg">
</picture>
</a>

**Comment by josxha** [comment]
I added protomaps themes version 4. They are available in version 1.5.0 of vector_map_tiles_pmtiles.
