### ISSUE TITLE
No labels showing

### ISSUE THREAD

**Issue by alejandrogiubel** [josxha/flutter_map_plugins#48]
### Package

vector_map_tiles_pmtiles

### Bug Description

Map labels are not showing

### Steps to Reproduce

Just use
```
final _futureTileProvider = PmTilesVectorTileProvider.fromSource(
  'https://build.protomaps.com/20241010.pmtiles',
);

VectorTileLayer(
  theme: ProtomapsThemes.lightV4(),
  tileProviders: TileProviders({
    'protomaps': snapshot.data!,
  }),
  fileCacheTtl: Duration.zero,
),
```

### Expected Results

A map with labels
<img width="603" alt="Captura de pantalla 2024-10-15 a la(s) 9 57 17 p m" src="https://github.com/user-attachments/assets/5095e7ce-7d24-493d-a4f1-725836c4ff68">

### Actual Results

![simulator_screenshot_295A714D-1507-4C05-8A40-5452235287F3](https://github.com/user-attachments/assets/36635214-8253-4b1b-ab4a-930933cea732)

### Code Sample

```dart
final _futureTileProvider = PmTilesVectorTileProvider.fromSource(
  'https://build.protomaps.com/20241010.pmtiles',
);

VectorTileLayer(
  theme: ProtomapsThemes.lightV4(),
  tileProviders: TileProviders({
    'protomaps': snapshot.data!,
  }),
  fileCacheTtl: Duration.zero,
),
```

### Platforms

ios

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/josxha) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/josxha/flutter_map_plugins/issues/48">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/josxha/flutter_map_plugins/issues/48/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/josxha/flutter_map_plugins/issues/48/pledge.svg">
</picture>
</a>

**Comment by josxha** [comment]
Thanks for opening this bug report, @alejandrogiubel. This is most likely a problem in the upstream [vector_tile_renderer](https://github.com/greensopinion/dart-vector-tile-renderer) package.

**Comment by alejandrogiubel** [comment]
Hello @josxha, sorry for returning to the topic, but I'm still having this problem, how did you manage to make the example images?

**Comment by josxha** [comment]
The screenshots where made in version 2 of Protomaps. It worked back then but Protomaps styles now use some expressions that are not supported by the vector_tile_renderer package. If you check the console, you can see that the unsupported expression get logged. For example:

```console
flutter: WARN: Unsupported expression syntax: [format, [coalesce, [get, name:en], [get, pgf:name3], [get, name3]], {}, 
, {}, [coalesce, [get, pgf:name], [get, name]], {text-font: [case, [==, [get, script], Devanagari], [literal, [Noto Sans Devanagari Regular v1]], [literal, [Noto Sans Regular]]]}, 
, {}, [coalesce, [get, pgf:name2], [get, name2]], {text-font: [case, [==, [get, script2], Devanagari], [literal, [Noto Sans Devanagari Regular v1]], [literal, [Noto Sans Regular]]]}]
```
You should be able to use either older protomaps style versions or create PMTiles files that use a completely different tile schema.
There is nothing we can do here in this plugin. I've seen that there are some recommended steps to debug this problem in https://github.com/greensopinion/dart-vector-tile-renderer/issues/101#issuecomment-2445862669. Did it brought some new insights?

**Comment by alejandrogiubel** [comment]
You're right I get those errors. I can't contribute much more at the moment because I don't have a deep understanding of the topic of map styles. I was afraid that the protomaps style would not be completely compatible. Switching to an older version of protomaps using an older version of the styles worked
