### ISSUE TITLE
[upstream] Exception when running in the VS Code debugger

### ISSUE THREAD

**Issue by josxha** [josxha/flutter_map_plugins#5]
VS Code has a bug where exceptions in async dart functions get caught even if they are actually handled.
The error message is:
> DioException (DioException [request cancelled]: The request was cancelled.)
![image](https://github.com/josxha/flutter_map_cache/assets/34318751/75c496d1-e120-4227-aef8-1d67f4a59e6e)

### This can be ignored, because the request cancelled exception gets handled by the package since flutter_map_cache version 1.3.1.

For more information about this issue see:
- https://github.com/cfug/dio/issues/1869#issuecomment-1694610280
- https://github.com/dart-lang/sdk/issues/47985

If you don't want the app to pause for those exceptions, you can uncheck the following debugger checkboxes:
![image](https://github.com/josxha/flutter_map_plugins/assets/34318751/a2229a63-9819-4221-8cb3-c53d14f9cd5f)

**Comment by PatrickWulfe** [comment]
Also having this issue

**Comment by PatrickWulfe** [comment]
Not a permanent solution, but I'm switching to just using a regular tile provider when kDebugMode == true to avoid this issue.
